import { type SeedStory, p, h, q, box, qa } from "./types";

export const FEATURE_STORIES: SeedStory[] = [
  {
    key: "spotlight-ithier",
    section: "spotlight",
    storyType: "INTERVIEW_PROFILE",
    title: "Ithier d'Aramon: how to get to X-HEC",
    campuses: ["paris"],
    status: "APPROVED",
    articleStatus: "APPROVED",
    priority: 84,
    isSpotlight: true,
    kicker: "People discover — student",
    headline: "\"The idea of knowing how to code with a business mindset\"",
    standfirst: "Ithier d'Aramon, 20, B3 in Paris, has been admitted to the Master of Science Data Science & AI for Business at École Polytechnique and HEC. He tells us how he got in.",
    targetLength: "LONG",
    template: "INTERVIEW",
    body: [
      qa("CAN YOU INTRODUCE YOURSELF?", "My name is Ithier d'Aramon, I'm 20 years old, I'm a B3 student and I've been admitted to the Master of Science Data Science & AI for Business, at the École Polytechnique and HEC."),
      qa("WHAT DOES THIS TRAINING INVOLVE?", "This is a joint programme between France's leading business school and the leading engineering school. We first spend a year at Polytechnique, focusing on maths and data courses. During this year, we are taught by Polytechnique professors. In the second year, we go to the HEC Paris campus to apply these hard skills to business. We continue our studies, still with the dual skills in data and business that we have already begun to acquire in our Bachelor's degree at Albert School."),
      qa("WHY DID YOU WANT TO JOIN THIS MASTER'S PROGRAMME?", "I think to answer that question, I need to answer the question of why I did Albert School in the first place. After my baccalauréat, I joined Albert School. I wanted to go to a business school, but with a bit more expertise, to avoid looking like everyone else. So my aim was to study something that would set me apart on the job market. That's where Albert School came in. The idea of knowing how to code with a business mindset or of 'doing business' with a technical mindset — that's what I was looking for. I really liked the technical side of it, so I joined our school.\n\nSo why did I want to join this famous master's programme? At the end of my three years at Albert School, I wanted another name on my CV to raise my profile (even though the Albert School masters seem to be very good). What's more, there are 60% international students in this Masters, so being in contact with people from other cultures seems very interesting to me. I also think that the structure of the programme, with one year at X and the other year at HEC, with its emphasis on theory applied to practice, appealed to me. And finally, of course, because these are the two best schools in France in their field!"),
      qa("HOW DID YOU GET IN?", "One of the most important things is to take the TAGE MAGE and get a very good score. You also need a C1 English test, so I took the IELTS. Of course, good grades at Albert School are also required.\n\nOn my CV, I've highlighted the 7 Business Deep Dives I've won, my 3-month internship at Axa, my 6-month internship at Partech (a French private equity investment firm). I also have another advantage: at the end of my internship, they offered me the chance to continue on a freelance basis. So since December, whenever I have half a day free, I go to Partech. And finally, I've put forward my role in the running association We Run Albert, which I co-founded and of which I was chairman.\n\nWhat's more, I had to provide two letters of recommendation: one from Benjamin Apra, my maths teacher, and one from my work placement supervisor, Partech's Chief Information Officer.\n\nAs my application was accepted, I had to take oral exams. The first part is a maths teacher who asks you knowledge questions. For half an hour, you're attacked with ten or so maths questions, at bac+3 level. The second part is an interview about your personality and how you feel about the school. I found it quite intimidating to find myself in front of a panel from Polytechnique and HEC.\n\nI think that Albert School really helped me to get in. In fact, the school is completely in line with the training we were looking for before this Masters. We're typically the profiles they're looking for, because we're unique with our combination of data and business. But in the end I got in and I'm proud of it!"),
      box("In a nutshell", ["A very good TAGE MAGE score", "Good grades", "7 BDD wins", "An internship at Partech, then freelance", "Co-founder and chairman of We Run Albert", "Letter of recommendation from Partech's CIO", "Very good score in the English test"]),
    ],
    pullQuotes: [{ text: "The idea of knowing how to code with a business mindset — that's what I was looking for.", attribution: "Ithier d'Aramon" }],
    media: [
      { file: "ithier-daramon-portrait.jpg", caption: "Ithier d'Aramon", kind: "photo", rights: "GREEN", role: "portrait" },
      { file: "ithier-daramon-wide.jpg", caption: "Ithier d'Aramon, B3 Paris", kind: "photo", rights: "GREEN", role: "hero" },
    ],
    facts: [
      { statement: "Ithier d'Aramon, 20, B3 student, has been admitted to the MSc Data Science & AI for Business at École Polytechnique and HEC.", category: "award", confidence: "VERIFIED_BY_SUBMISSION", sourceIndex: 0 },
      { statement: "The programme spends the first year at Polytechnique and the second at HEC Paris; 60% of its students are international.", category: "other", confidence: "STATED_BY_CONTRIBUTOR", sourceIndex: 0 },
      { statement: "He highlighted 7 BDD wins, a 3-month internship at Axa and a 6-month internship at Partech, continued freelance since December.", category: "other", confidence: "STATED_BY_CONTRIBUTOR", sourceIndex: 0 },
      { statement: "He co-founded and chaired the running association We Run Albert.", category: "other", confidence: "STATED_BY_CONTRIBUTOR", sourceIndex: 0 },
      { statement: "Letters of recommendation came from Benjamin Apra (maths teacher) and Partech's Chief Information Officer.", category: "person", confidence: "STATED_BY_CONTRIBUTOR", sourceIndex: 0 },
    ],
    quotes: [
      { text: "The idea of knowing how to code with a business mindset or of 'doing business' with a technical mindset — that's what I was looking for.", speaker: "Ithier d'Aramon", role: "B3 Paris", sourceIndex: 0, pullQuote: true },
      { text: "But in the end I got in and I'm proud of it!", speaker: "Ithier d'Aramon", role: "B3 Paris", sourceIndex: 0 },
    ],
    people: [
      { name: "Ithier d'Aramon", role: "INTERVIEWEE", campus: "paris", program: "B3" },
      { name: "Benjamin Apra", role: "MENTIONED" },
    ],
    organisations: [
      { name: "École Polytechnique", type: "SCHOOL", role: "MENTIONED" },
      { name: "HEC Paris", type: "SCHOOL", role: "MENTIONED" },
      { name: "Partech", type: "COMPANY", role: "EMPLOYER" },
      { name: "Axa", type: "COMPANY", role: "EMPLOYER" },
      { name: "We Run Albert", type: "ASSOCIATION", role: "MENTIONED" },
    ],
    submissions: [
      {
        contributor: "ithier",
        storyType: "INTERVIEW_PROFILE",
        title: "Interview: my admission to the X-HEC MSc Data Science & AI for Business",
        campuses: ["paris"],
        description:
          "CAN YOU INTRODUCE YOURSELF? My name is Ithier d'Aramon, I'm 20 years old, I'm a B3 student and I've been admitted to the Master of Science Data Science & AI for Business, at the École Polytechnique and HEC. WHAT DOES THIS TRAINING INVOLVE? A joint programme between France's leading business school and the leading engineering school: a first year at Polytechnique focused on maths and data, taught by Polytechnique professors; a second year at HEC Paris to apply these hard skills to business. WHY? After my baccalauréat I joined Albert School because I wanted a business school with more expertise, to avoid looking like everyone else: knowing how to code with a business mindset, or doing business with a technical mindset. At the end of my three years I wanted another name on my CV; 60% of the Masters students are international; one year at X, one at HEC, theory applied to practice; and they are the two best schools in France in their field. HOW DID YOU GET IN? A very good TAGE MAGE score, a C1 English test (IELTS), good grades. On my CV: the 7 Business Deep Dives I've won, my 3-month internship at Axa, my 6-month internship at Partech (a French private equity firm) — at the end they offered me to continue freelance, so since December whenever I have half a day free I go to Partech — and my role in We Run Albert, the running association I co-founded and chaired. Two letters of recommendation: Benjamin Apra, my maths teacher, and my internship supervisor, Partech's CIO. Then oral exams: half an hour of maths questions at bac+3 level, then a personality interview in front of a panel from Polytechnique and HEC — quite intimidating. Albert School really helped: we're typically the profiles they look for, with our combination of data and business. In the end I got in and I'm proud of it!",
        peopleInvolved: "Ithier d'Aramon, Benjamin Apra",
        organisationsInvolved: "École Polytechnique, HEC Paris, Partech, Axa, We Run Albert",
        whyItMatters: "First Albert student admitted to this joint X-HEC master's; a concrete roadmap for B3s.",
        media: ["ithier-daramon-portrait.jpg", "ithier-daramon-wide.jpg"],
        status: "ACCEPTED",
        daysAfterOpen: 2,
      },
    ],
    aiScores: { schoolRelevance: 92, studentRelevance: 95, uniqueness: 88, campusImportance: 70, timeliness: 80, editorialInterest: 90, visualRichness: 60, institutionalImportance: 85, businessDataRelevance: 78 },
  },
  {
    key: "project-kaern",
    section: "projects",
    storyType: "STUDENT_PROJECT",
    title: "KÆRN: four students turn ideas into digital solutions",
    campuses: ["marseille"],
    status: "APPROVED",
    articleStatus: "APPROVED",
    priority: 82,
    kicker: "Student startup — Marseille",
    headline: "KÆRN: when four students turn ideas into digital solutions",
    standfirst: "Alexis Meniante, Théo Fontes, Noah Soulisse and Jules Bertin founded a digital agency between two courses on the Marseille campus. Their first name was already taken; their first clients were not.",
    targetLength: "MEDIUM",
    template: "ARTICLE_HERO",
    body: [
      h("AN ADVENTURE BORN AT ALBERT SCHOOL"),
      p("Alexis Meniante, Théo Fontes, Noah Soulisse and Jules Bertin, four students from Albert School, have put their skills and passion for digital technology to work in a promising new company: KÆRN. Their mission? To support companies, from start-ups to major groups, in their digital transformation."),
      p("\"We design the entire digital environment, from the landing page to the mobile application, including bespoke CRM and growth hacking strategies,\" explains Alexis. The idea was born out of meetings at school events. \"A lot of companies came to us because they had a real need for digital support. We said to ourselves: why not professionalise these services?\", says Théo."),
      h("OVERCOMING CHALLENGES, ONE PROJECT AT A TIME"),
      p("Today, KÆRN already has a number of customers, including Le Méridional, Inclusive Brains (voted best French start-up) and innovative companies such as Telaqua, supported by the CMA CGM investment fund. \"Each project is unique. You have to immerse yourself in the customer's business to come up with a relevant solution,\" Alexis emphasises."),
      p("Their biggest challenge? Understanding the specific needs of each company and maintaining the link with customers with overloaded agendas. That's where we see the importance of a close-knit team. But their adventure wasn't without its pitfalls: while their first name, KERNEL, was already being heard throughout Albert School Marseille, they realised that it had already been registered! They had to rethink everything and finally chose KÆRN, a short and distinctive name."),
      h("AN AMBITIOUS AND PRAGMATIC VISION"),
      p("In a year's time, KÆRN wants to refine its offering and stand out from the crowd. In the long term, their aim is to create an ecosystem of studio tech start-ups in the PACA region. Their strategy for growth? Simply not to miss a step. Today, thanks to the ecosystem at Grand Central (where the Marseille campus is located), they are already finding customers quite easily. What they really need now is to develop their skills. For the moment, they are honouring their contracts in the best possible way by familiarising themselves with the tools and the world of entrepreneurship."),
      h("BETWEEN COURSES AND ENTREPRENEURSHIP: THE DAILY CHALLENGE"),
      p("Managing studies and business is not always easy, but the team finds its balance. \"It's stimulating, sometimes tiring, but the four of us help each other out,\" they conclude. One thing is certain: KÆRN is much more than a student project. It's a human and professional adventure that shows that innovation can be born... between two courses. Follow their project on kaern.fr."),
      h("IF YOU COULD CONVINCE SOMEONE TO JOIN YOUR PROJECT IN ONE SENTENCE, WHAT WOULD YOU SAY?"),
      q("There's no better way to put what you learn at Albert into practice than by working on real projects that meet real business needs.", "The KÆRN team"),
    ],
    pullQuotes: [{ text: "There's no better way to put what you learn at Albert into practice than by working on real projects that meet real business needs.", attribution: "The KÆRN team" }],
    media: [
      { file: "kaern-team.jpg", caption: "The KÆRN team", kind: "photo", rights: "GREEN", role: "hero" },
      { file: "kaern-header.jpg", caption: "KÆRN logo", kind: "logo", rights: "GREEN", role: "logo" },
    ],
    facts: [
      { statement: "KÆRN was founded by Albert School students Alexis Meniante, Théo Fontes, Noah Soulisse and Jules Bertin.", category: "person", confidence: "VERIFIED_BY_SUBMISSION", sourceIndex: 0 },
      { statement: "KÆRN's clients include Le Méridional, Inclusive Brains and Telaqua.", category: "organisation", confidence: "STATED_BY_CONTRIBUTOR", sourceIndex: 0 },
      { statement: "The company was first called KERNEL, a name that turned out to be already registered.", category: "other", confidence: "VERIFIED_BY_SUBMISSION", sourceIndex: 0 },
      { statement: "The Marseille campus is located at Grand Central.", category: "other", confidence: "STATED_BY_CONTRIBUTOR", sourceIndex: 0 },
    ],
    quotes: [
      { text: "We design the entire digital environment, from the landing page to the mobile application, including bespoke CRM and growth hacking strategies.", speaker: "Alexis Meniante", role: "KÆRN co-founder", sourceIndex: 0 },
      { text: "A lot of companies came to us because they had a real need for digital support. We said to ourselves: why not professionalise these services?", speaker: "Théo Fontes", role: "KÆRN co-founder", sourceIndex: 0 },
      { text: "There's no better way to put what you learn at Albert into practice than by working on real projects that meet real business needs.", speaker: "The KÆRN team", sourceIndex: 0, pullQuote: true },
    ],
    people: [
      { name: "Alexis Meniante", role: "FOUNDER", campus: "marseille" },
      { name: "Théo Fontes", role: "FOUNDER", campus: "marseille" },
      { name: "Noah Soulisse", role: "FOUNDER", campus: "marseille" },
      { name: "Jules Bertin", role: "FOUNDER", campus: "marseille" },
    ],
    organisations: [
      { name: "KÆRN", type: "STARTUP", role: "SUBJECT" },
      { name: "Le Méridional", type: "COMPANY", role: "MENTIONED" },
      { name: "Inclusive Brains", type: "STARTUP", role: "MENTIONED" },
      { name: "Telaqua", type: "STARTUP", role: "MENTIONED" },
    ],
    submissions: [
      {
        contributor: "alexis",
        storyType: "STUDENT_PROJECT",
        title: "KÆRN — our digital agency founded at Albert School Marseille",
        campuses: ["marseille"],
        description:
          "We are four students from Albert School — Alexis Meniante, Théo Fontes, Noah Soulisse and Jules Bertin — and we founded KÆRN, a company that supports companies, from start-ups to major groups, in their digital transformation. We design the entire digital environment, from the landing page to the mobile application, including bespoke CRM and growth hacking strategies. The idea was born out of meetings at school events: a lot of companies came to us because they had a real need for digital support, so we decided to professionalise these services. Customers so far: Le Méridional, Inclusive Brains (voted best French start-up), Telaqua (supported by the CMA CGM investment fund). Each project is unique — you have to immerse yourself in the customer's business. Biggest challenge: understanding each company's specific needs and keeping the link with customers with overloaded agendas. Funny pitfall: our first name, KERNEL, was already registered, so we chose KÆRN. In a year we want to refine our offering; long term, an ecosystem of studio tech start-ups in the PACA region. Thanks to the ecosystem at Grand Central (where the Marseille campus is) we find customers quite easily. Managing studies and business is stimulating, sometimes tiring, but the four of us help each other out. Website: kaern.fr",
        peopleInvolved: "Alexis Meniante, Théo Fontes, Noah Soulisse, Jules Bertin",
        organisationsInvolved: "KÆRN, Le Méridional, Inclusive Brains, Telaqua, CMA CGM",
        whyItMatters: "A real company created by Albert students, with real clients, born on the Marseille campus.",
        quotes: "\"There's no better way to put what you learn at Albert into practice than by working on real projects that meet real business needs.\"",
        urls: ["https://kaern.fr"],
        media: ["kaern-team.jpg", "kaern-header.jpg"],
        status: "ACCEPTED",
        daysAfterOpen: 3,
      },
    ],
    aiScores: { schoolRelevance: 86, studentRelevance: 90, uniqueness: 84, campusImportance: 88, timeliness: 70, editorialInterest: 88, visualRichness: 62, institutionalImportance: 72, businessDataRelevance: 70 },
  },
  {
    key: "spotlight-boris",
    section: "spotlight",
    storyType: "INTERVIEW_PROFILE",
    title: "Boris Bernard, the Hugo Décrypte of Playmobil",
    campuses: [],
    status: "APPROVED",
    articleStatus: "APPROVED",
    priority: 68,
    kicker: "People discover — admin",
    headline: "\"I'm the Hugo Décrypte of Playmobil!\"",
    standfirst: "Boris Bernard is Digital Marketing Manager at Albert School. Outside work he hosts Monsieur Playmo, a YouTube channel with over 290 videos and several million views — soon to become Monsieur Bobo.",
    byline: "Ines Hocine",
    targetLength: "MEDIUM",
    template: "PROFILE",
    body: [
      p("Boris is Digital Marketing Manager at Albert School, but his creativity extends far beyond digital campaigns. Outside of work, he hosts the YouTube channel Monsieur Playmo, where he stages Playmobil adventures."),
      h("CREATING TO OVERCOME LONELINESS AND REDISCOVER YOUR CHILDHOOD"),
      p("Born in Bordeaux, Boris felt the need to develop his creativity at an early age. Using his Playmobil, he began to create small filmed scenes, without any technical experience. His first sets were simple, but very quickly the desire to tell stories took over. He learned how to film and edit, and discovered a real pleasure in building his own worlds."),
      p("It was by developing this passion that he chose to focus his studies on communications and advertising, before being recruited by Albert School thanks to his work on Monsieur Playmo. Since launching his channel in 2015, Boris has published over 290 videos, racking up several million views. It's an adventure he's led with patience and passion, far from any pressure."),
      h("FAITHFUL TO HIS PASSION AND FREE IN HIS CHOICES"),
      p("Little by little, his world is attracting a loyal following. He's even been lucky enough to sign a dozen partnerships, including with Blanc Mangé Coco, Kapla and the Futuroscope! He regularly takes part in exhibitions where huge 20–30 m² displays bring to life a Napoleonic battle, for example. His authentic work has not gone unnoticed: France Info devoted an article to him, praising his creative and atypical career."),
      p("As well as the content, it's also his personal project that has helped him land internships and work-study placements in digital marketing. A fine illustration for Albert School students: passion can open unexpected professional doors."),
      h("A NEW STAGE: MONSIEUR BOBO"),
      p("To mark the 10th anniversary of his YouTube channel, Boris is expanding his content to include the worlds of exhibitions, interior design and fashion. Monsieur Playmo will soon become Monsieur Bobo, to reflect this creative evolution."),
    ],
    media: [
      { file: "boris-bernard.jpg", caption: "Boris Bernard", kind: "photo", rights: "GREEN", role: "portrait" },
      { file: "monsieur-bobo-logo.jpg", caption: "Future Monsieur Bobo logo", kind: "logo", rights: "GREEN", role: "logo" },
    ],
    facts: [
      { statement: "Boris Bernard is Digital Marketing Manager at Albert School and hosts the YouTube channel Monsieur Playmo.", category: "person", confidence: "VERIFIED_BY_SUBMISSION", sourceIndex: 0 },
      { statement: "Since 2015 he has published over 290 videos with several million views.", category: "metric", confidence: "STATED_BY_CONTRIBUTOR", sourceIndex: 0 },
      { statement: "He has signed a dozen partnerships, including Blanc Mangé Coco, Kapla and the Futuroscope, and France Info devoted an article to him.", category: "other", confidence: "STATED_BY_CONTRIBUTOR", sourceIndex: 0 },
      { statement: "Monsieur Playmo will become Monsieur Bobo for the channel's 10th anniversary.", category: "other", confidence: "VERIFIED_BY_SUBMISSION", sourceIndex: 0 },
    ],
    people: [{ name: "Boris Bernard", role: "INTERVIEWEE" }],
    organisations: [{ name: "France Info", type: "MEDIA", role: "MENTIONED" }],
    submissions: [
      {
        contributor: "ines",
        storyType: "INTERVIEW_PROFILE",
        title: "Portrait: Boris Bernard, Monsieur Playmo",
        campuses: [],
        description:
          "Boris Bernard is Digital Marketing Manager at Albert School, but outside work he hosts the YouTube channel Monsieur Playmo, where he stages Playmobil adventures. Born in Bordeaux, he started filming small scenes with his Playmobil without technical experience, learned to film and edit, then focused his studies on communications and advertising before being recruited by Albert School thanks to his work on Monsieur Playmo. Since launching the channel in 2015: over 290 videos, several million views. A dozen partnerships (Blanc Mangé Coco, Kapla, the Futuroscope), exhibitions with 20–30 m² displays (a Napoleonic battle!), an article on France Info. The personal project helped him land internships and work-study placements in digital marketing — passion can open unexpected professional doors. For the channel's 10th anniversary, Monsieur Playmo becomes Monsieur Bobo, expanding to exhibitions, interior design and fashion. He describes himself as 'the Hugo Décrypte of Playmobil'.",
        peopleInvolved: "Boris Bernard",
        quotes: "\"I'm the Hugo Décrypte of Playmobil!\" — Boris Bernard",
        media: ["boris-bernard.jpg", "monsieur-bobo-logo.jpg"],
        status: "ACCEPTED",
        daysAfterOpen: 4,
      },
    ],
    aiScores: { schoolRelevance: 62, studentRelevance: 70, uniqueness: 90, campusImportance: 50, timeliness: 60, editorialInterest: 84, visualRichness: 66, institutionalImportance: 55, businessDataRelevance: 40 },
  },
];
