import { type SeedStory, p, h, l, box } from "./types";

export const CAMPUS_STORIES: SeedStory[] = [
  {
    key: "campus-prize-list",
    section: "campus-life",
    storyType: "ANECDOTE",
    title: "School prize list: who can beat us?",
    campuses: [],
    status: "APPROVED",
    articleStatus: "APPROVED",
    priority: 64,
    kicker: "Anecdotes & student life",
    headline: "School prize list: who can beat us?",
    standfirst: "A modest, entirely objective comparison of Albert School with ESCP, EDHEC, HEC, Louis Vuitton and Harvard.",
    targetLength: "MEDIUM",
    template: "SHORTS",
    body: [
      h("B1 EUGENIA > M2 HEC"),
      p("During a business automation BDD between Eugenia's Bachelors 1 and the HTP startup at Station F, the startup much preferred the work of the B1s to that of a team of HEC Masters 2. And for a similar amount of time."),
      h("ALBERT > ESCP"),
      p("At an ESCP event, Albert School students proved to be far more useful and dominant in the groups working on the assignments. Remember that this school is ranked 3rd or 4th in France."),
      h("ALBERT > EDHEC"),
      p("The double degree with EDHEC is as follows: EDHEC students go on to the 2nd year at Albert School after their 3rd year, while the Alberts go on to the 3rd year at EDHEC after their second year. This is because EDHEC claims that Albert School students have a better level."),
      h("ALBERT ≥ LOUIS VUITTON"),
      p("Following the Louis Vuitton 2023/24 BDD, the four best groups went to LV to present their ideas on 7 March 2024 to the head of business development. Each group focused on the implementation of jewellery in Korea, and a little later, Louis Vuitton opened the first watch and jewellery boutique in Korea. Either Louis Vuitton listened to them, or the solutions were really relevant."),
      h("ALBERT > HARVARD"),
      p("According to the Financial Times, Albert School could dethrone Harvard, the world's top 1, before 2030. (Well, that's not true, but everything else is true!)"),
      h("ALBERT = X + HEC"),
      p("Polytechnique (top 1 engineering school) and HEC (top 1 business school) offer two joint degrees: the Master of Science Data for Business and the Master of Science X-HEC Entrepreneurs. Ithier d'Aramon in B3 was admitted to the Master Data for Business, as was Amine Djoumai, also in B3, to the Master X-HEC Entrepreneurs."),
    ],
    media: [{ file: "prize-list-photo.jpg", caption: "Albert students at work", kind: "photo", rights: "YELLOW", role: "hero" }],
    facts: [
      { statement: "Ithier d'Aramon (B3) was admitted to the MSc Data for Business and Amine Djoumai (B3) to the MSc X-HEC Entrepreneurs.", category: "award", confidence: "STATED_BY_CONTRIBUTOR", sourceIndex: 0 },
      { statement: "After the Louis Vuitton 2023/24 BDD, the four best groups presented their ideas at LV on 7 March 2024.", category: "date", confidence: "STATED_BY_CONTRIBUTOR", sourceIndex: 0 },
      { statement: "The 'Albert > Harvard' item is explicitly a joke and must be kept with its disclaimer.", category: "other", confidence: "VERIFIED_BY_SUBMISSION", sourceIndex: 0 },
    ],
    people: [
      { name: "Ithier d'Aramon", role: "MENTIONED", campus: "paris", program: "B3" },
      { name: "Amine Djoumai", role: "MENTIONED", campus: "paris", program: "B3" },
    ],
    organisations: [
      { name: "ESCP", type: "SCHOOL", role: "MENTIONED" },
      { name: "EDHEC", type: "SCHOOL", role: "MENTIONED" },
      { name: "Louis Vuitton", type: "COMPANY", role: "MENTIONED" },
    ],
    submissions: [
      {
        contributor: "milan",
        storyType: "ANECDOTE",
        title: "School prize list — who can beat us? (anecdotes)",
        campuses: [],
        description:
          "Short anecdotes for the student life pages. B1 EUGENIA > M2 HEC: during a business automation BDD between Eugenia's Bachelors 1 and the HTP startup at Station F, the startup much preferred the work of the B1s to that of a team of HEC Masters 2, for a similar amount of time. ALBERT > ESCP: at an ESCP event, Albert students were far more useful and dominant in the working groups — and ESCP is ranked 3rd or 4th in France. ALBERT > EDHEC: in the double degree, EDHEC students join Albert's 2nd year after their 3rd year, while Alberts join EDHEC's 3rd year after their 2nd year, because EDHEC claims Albert students have a better level. ALBERT ≥ LOUIS VUITTON: after the LV 2023/24 BDD, the four best groups presented on 7 March 2024 to the head of business development, each on jewellery in Korea; a little later LV opened its first watch and jewellery boutique in Korea. ALBERT > HARVARD: according to the Financial Times, Albert could dethrone Harvard before 2030 (not true, but everything else is!). ALBERT = X + HEC: Ithier d'Aramon (B3) admitted to the MSc Data for Business, Amine Djoumai (B3) to the MSc X-HEC Entrepreneurs.",
        peopleInvolved: "Ithier d'Aramon, Amine Djoumai",
        organisationsInvolved: "Eugenia, HEC, ESCP, EDHEC, Louis Vuitton, Station F",
        media: ["prize-list-photo.jpg"],
        status: "ACCEPTED",
        daysAfterOpen: 5,
      },
    ],
    warnings: [{ code: "TONE_CHECK", message: "Comparative claims about other schools are anecdotal; keep the humorous framing and the Harvard disclaimer.", severity: "info" }],
    aiScores: { schoolRelevance: 80, studentRelevance: 88, uniqueness: 82, campusImportance: 50, timeliness: 60, editorialInterest: 90, visualRichness: 30, institutionalImportance: 50, businessDataRelevance: 40 },
  },
  {
    key: "campus-jonquille-run",
    section: "campus-life",
    storyType: "EVENT_RECAP",
    title: "The Jonquille Run",
    campuses: ["paris"],
    eventDateText: "Saturday 22 March 2025",
    status: "APPROVED",
    articleStatus: "APPROVED",
    priority: 66,
    kicker: "Student life — Paris",
    headline: "1 km for €1: the Jonquille Run covers 250 km for the Institut Curie",
    standfirst: "On 22 March, We Run Albert and the BDS Albears brought students to Stade Beaugrenelle to run against cancer — and two champions ran a half-marathon on their own.",
    byline: "Milan Viallet",
    targetLength: "SHORT",
    template: "ARTICLE_HERO",
    body: [
      h("1 KM FOR 1€"),
      p("On Saturday 22 March, Stade Beaugrenelle played host to the Daffodil Run! Organised by We Run Albert and the BDS Albears, the event brought together students to run for a great cause: for every kilometre run, €1 was donated to the Institut Curie in the fight against cancer."),
      p("In the sunshine and in an incredible atmosphere, everyone ran at their own pace and a total of 250 km was covered by all the participants, a feat that deserves to be highlighted! The festive atmosphere, the music, the free food and drink... everything was perfect for a fantastic afternoon!"),
      p("A special mention to Eléonore de Bokay and Madeleine Landry, our two champions, who took on the incredible challenge of running a half-marathon on their own! A big well done to all the participants! We look forward to the next edition!"),
    ],
    media: [
      { file: "jonquille-run-1.jpg", caption: "The Jonquille Run at Stade Beaugrenelle", credit: "© Milan Viallet", photographer: "Milan Viallet", kind: "photo", rights: "GREEN", role: "hero" },
      { file: "jonquille-run-runners.png", caption: "Runners", credit: "© Pierre-Louis Lacorde", photographer: "Pierre-Louis Lacorde", kind: "photo", rights: "GREEN", role: "gallery" },
    ],
    facts: [
      { statement: "The Jonquille (Daffodil) Run took place on Saturday 22 March 2025 at Stade Beaugrenelle, organised by We Run Albert and the BDS Albears.", category: "date", confidence: "VERIFIED_BY_SUBMISSION", sourceIndex: 0 },
      { statement: "€1 per kilometre was donated to the Institut Curie; participants covered 250 km in total.", category: "metric", confidence: "STATED_BY_CONTRIBUTOR", sourceIndex: 0 },
      { statement: "Eléonore de Bokay and Madeleine Landry each ran a half-marathon.", category: "person", confidence: "STATED_BY_CONTRIBUTOR", sourceIndex: 0 },
    ],
    people: [
      { name: "Eléonore de Bokay", role: "MENTIONED", campus: "paris" },
      { name: "Madeleine Landry", role: "MENTIONED", campus: "paris" },
    ],
    organisations: [
      { name: "We Run Albert", type: "ASSOCIATION", role: "PARTNER" },
      { name: "BDS Albears", type: "ASSOCIATION", role: "PARTNER" },
      { name: "Institut Curie", type: "INSTITUTION", role: "MENTIONED" },
    ],
    event: { title: "The Jonquille Run", dateText: "Saturday 22 March 2025", location: "Stade Beaugrenelle, Paris", campus: "paris", isUpcoming: false, organiser: "We Run Albert & BDS Albears" },
    submissions: [
      {
        contributor: "milan",
        storyType: "EVENT_RECAP",
        title: "The Jonquille Run — 250 km for the Institut Curie",
        campuses: ["paris"],
        eventDateText: "Saturday 22 March",
        description:
          "On Saturday 22 March, Stade Beaugrenelle hosted the Daffodil Run, organised by We Run Albert and the BDS Albears: for every kilometre run, €1 was donated to the Institut Curie in the fight against cancer. Sunshine, incredible atmosphere, everyone at their own pace — 250 km covered in total. Music, free food and drink. Special mention to Eléonore de Bokay and Madeleine Landry, who ran a half-marathon on their own. Photos: mine (© Milan Viallet) and one by Pierre-Louis Lacorde.",
        peopleInvolved: "Eléonore de Bokay, Madeleine Landry",
        organisationsInvolved: "We Run Albert, BDS Albears, Institut Curie",
        media: ["jonquille-run-1.jpg", "jonquille-run-runners.png"],
        status: "ACCEPTED",
        daysAfterOpen: 1,
      },
    ],
    aiScores: { schoolRelevance: 72, studentRelevance: 84, uniqueness: 60, campusImportance: 78, timeliness: 66, editorialInterest: 74, visualRichness: 76, institutionalImportance: 50, businessDataRelevance: 10 },
  },
  {
    key: "assoc-albertine",
    section: "associations",
    storyType: "ASSOCIATION",
    title: "New association: Albertine",
    campuses: ["marseille", "paris"],
    status: "APPROVED",
    articleStatus: "APPROVED",
    priority: 70,
    kicker: "New association",
    headline: "Albertine: promoting women in tech, from open days to Google's headquarters",
    standfirst: "Founded by female students and open to all, Albertine wants to inspire, connect and support — starting with a mentoring network and a Paris event coming soon.",
    byline: "Colène Geoffroy",
    targetLength: "MEDIUM",
    template: "ARTICLE_TWO_COLUMN",
    body: [
      p("A new energy is blowing through Albert School with Albertine, the association founded by female students to promote gender equality in the tech professions."),
      h("BUT, ALBERTINE, WHAT EXACTLY IS THIS NEW ASSOCIATION?"),
      p("It's an inclusive initiative, open to all, aimed at combating gender stereotypes and promoting the presence of women in the tech industry: moving the field towards greater gender diversity. Today, only 15% of tech students are women. What's more, according to INSEE, women hold just 24% of jobs in the digital professions in France. These are figures that are struggling to change for the better, proving the lack of visible female role models in this field. Elisabeth Borne, the French Minister for Education, launched an action plan to mobilise the educational community and parents to encourage young girls to study engineering and digital sciences."),
      p("As we all know, at the JPO, female students are all the more at ease when they are assured of the presence of other women. Providing this legitimacy is one of the pillars of the association."),
      h("A COMMITTED FOUNDER AND A CLOSE-KNIT TEAM"),
      p("Lison Szymkowicz, President of Albertine, came up with the original idea for this initiative. She is 100% committed to the project and has surrounded herself with a motivated team. Together, these students have built the foundations of this ambitious and caring association."),
      h("OUR MISSION: TO INSPIRE, CONNECT AND SUPPORT"),
      p("Albertine is committed to taking real action:"),
      l([
        "Create a mentoring network between high school and university students and professionals through mentorships, workshops or personalised meetings and coaching.",
        "Establish a platform for exchange and support between students, so that everyone can express their personal, academic or social problems in a confidential, healthy and non-judgemental environment. One counsellor per campus will be able to provide daily support and advice to students.",
        "Join associations such as WoMines PSL or Elles bougent and take part in events such as \"Elles innovent pour le Numérique\", which brings together secondary school girls and students from 7 (and we hope 8!) schools at Google headquarters.",
        "Raise awareness of gender issues within the student community through think tanks, conferences and workshops.",
      ]),
      h("JOIN ALBERTINE"),
      p("Albertine is the Albert School student office where everyone is welcome to join in the adventure. Registration is open to everyone, via the link in the biography of the albertine.school Instagram account, by sending us a message directly or by contacting us face-to-face. And soon, two key figures, a godmother and a godfather, will embody the values and commitments of the association. Get ready, an event in Paris is coming soon..."),
      box("Why \"Albertine\"?", ["Because she is one of the freest, most complex and most brilliant female characters in Proust's In Search of Lost Time: a figure as intelligent as she is impertinent, embodying the ambitions of our association."]),
    ],
    media: [
      { file: "lison-szymkowicz.jpg", caption: "Lison Szymkowicz, President of Albertine", kind: "photo", rights: "GREEN", role: "portrait" },
      { file: "albertine-logo.png", caption: "Albertine", kind: "logo", rights: "GREEN", role: "logo" },
    ],
    facts: [
      { statement: "Albertine is a new Albert School association founded by female students to promote gender equality in tech; Lison Szymkowicz is its President.", category: "organisation", confidence: "VERIFIED_BY_SUBMISSION", sourceIndex: 0 },
      { statement: "Only 15% of tech students are women; women hold 24% of digital jobs in France (INSEE).", category: "metric", confidence: "STATED_BY_CONTRIBUTOR", sourceIndex: 0, notes: "External statistics: add the INSEE reference." },
      { statement: "Registration is open via the albertine.school Instagram account; an event in Paris is planned.", category: "other", confidence: "VERIFIED_BY_SUBMISSION", sourceIndex: 0 },
    ],
    people: [{ name: "Lison Szymkowicz", role: "FOUNDER", campus: "marseille", program: "B1" }],
    organisations: [
      { name: "Albertine", type: "ASSOCIATION", role: "SUBJECT" },
      { name: "WoMines PSL", type: "ASSOCIATION", role: "MENTIONED" },
      { name: "Elles bougent", type: "ASSOCIATION", role: "MENTIONED" },
    ],
    submissions: [
      {
        contributor: "lison",
        storyType: "ASSOCIATION",
        title: "Albertine — a new association for women in tech",
        campuses: ["marseille", "paris"],
        description:
          "Albertine is the association founded by female students to promote gender equality in the tech professions: an inclusive initiative, open to all, combating gender stereotypes and promoting the presence of women in tech. Only 15% of tech students are women; according to INSEE, women hold just 24% of jobs in the digital professions in France. Elisabeth Borne launched an action plan to encourage young girls to study engineering and digital sciences. At the JPO, female students are more at ease when other women are present — providing this legitimacy is one of our pillars. I (Lison Szymkowicz) am the President; a motivated team built the foundations. Our missions: a mentoring network between high school and university students and professionals (mentorships, workshops, coaching); a confidential platform for exchange and support with one counsellor per campus; join associations such as WoMines PSL or Elles bougent and take part in events like 'Elles innovent pour le Numérique' at Google headquarters (7, hopefully 8, schools); raise awareness through think tanks, conferences and workshops. Registration via the link in the bio of the albertine.school Instagram account, by message or face-to-face. Soon a godmother and a godfather will embody our values. Why Albertine? One of the freest, most complex and most brilliant female characters in Proust's In Search of Lost Time. An event in Paris is coming soon.",
        peopleInvolved: "Lison Szymkowicz",
        organisationsInvolved: "Albertine, WoMines PSL, Elles bougent, Google",
        urls: ["https://www.instagram.com/albertine.school"],
        media: ["lison-szymkowicz.jpg", "albertine-logo.png"],
        status: "ACCEPTED",
        daysAfterOpen: 3,
      },
    ],
    aiScores: { schoolRelevance: 82, studentRelevance: 86, uniqueness: 76, campusImportance: 80, timeliness: 72, editorialInterest: 80, visualRichness: 50, institutionalImportance: 70, businessDataRelevance: 30 },
  },
  {
    key: "campus-spi-dauphine",
    section: "campus-life",
    storyType: "EVENT_RECAP",
    title: "SPI Dauphine: Albert School enters the race",
    campuses: ["paris"],
    eventDateText: "April 2025, Bay of Saint-Tropez",
    status: "APPROVED",
    articleStatus: "APPROVED",
    priority: 72,
    kicker: "Student life — Albert Crew",
    headline: "SPI Dauphine: Albert School enters the race",
    standfirst: "Five days, 45 teams, wind, rain and one skipper called Yann: for its first regatta, the newly founded Albert Crew finished 12th — and 3rd in the beer jug competition.",
    byline: "Ines Hocine",
    targetLength: "LONG",
    template: "ARTICLE_HERO",
    body: [
      p("While the papers pile up and the exams approach, some people have chosen to take to the open sea: mentally, athletically and collectively. The sun shone, the rain poured: five days to test our motivation. Welcome to the SPI Dauphine, one of the biggest student sports events in France, bringing together nearly 1,000 students and around fifty teams in the Bay of Saint-Tropez. You come for the competition, you stay for the atmosphere, and you leave with memories, a few bruises and a headache."),
      p("This year, Albert School took part for the very first time. It was a big first, orchestrated by Joseph Abdo, Flore Jaskulke and Victor de l'Epine, who set up the Albert Crew association and got a whole team on board. Sport, commitment and recyclable bottles."),
      h("HEADING FOR ADVENTURE: RAIN, PERFORMANCE AND (MINOR) PROBLEMS"),
      p("On board, there was wind, rain, uncertainty... and fortunately Yann, our skipper. A real captain in a storm, he kept the crew on the right track, offering technical advice and good humour. Without him, this week wouldn't have had the same flavour (or the same trajectory). We can't wait to meet up with him again next year for new adventures."),
      p("Despite some technical problems with our boat and some wild weather, we held on to finish 12th out of 45 teams, an honourable performance for a first-time entrant, especially with only five races to go. And because we never do things by halves, we also finished 3rd in the beer jug competition, a podium finish we hadn't even anticipated, but one we're pretty proud of (thanks Albert)."),
      p("How could we have thought that the weather in Saint-Tropez would be fine in April? First mistake. In terms of wardrobe preparation, we were closer to a muddy festival than a chic regatta: soaked socks and sweatshirts to be wrung out. Next time, it'll be mandatory oilskins for everyone."),
      h("ONBOARD ANECDOTES: OSCAR, THE TIGHTROPE WALKER AND OTHER SOAKED MEMORIES"),
      p("On our first trip out to sea, in pouring rain and strong winds, Oscar experienced gravity in his own way: half thrown out of the boat, he was saved at the last minute by the small safety cable. Fun fact: Oscar is still alive and didn't fall overboard. We even have a mythical photo immortalising the moment! Because yes, our first instinct was to take a photo of him... Some even found the courage to jump into the water for an icy swim, just to prove that hypothermia is an extreme sport in its own right."),
      p("But beyond the anecdotes, it was above all a team that pulled together under the storms: Emilie Paulis, Prisca Nobile, Oscar Mathey, Simon Flasaquier, Ines Hocine, Léo Wang, Constantin Vuillier, Albert Curtil, Vadim Capton, Matheo Pradels and Sulian Brouard-Heulluy. A team that never gave up, even in the rain, technical difficulties or fatigue."),
      h("ACKNOWLEDGEMENTS AND NEXT STEPS"),
      p("Thanks to Centric Software for trusting us right from our first steps on the water. A special mention goes to Bruce, EMEAR & LATAM Director of Partner Services at Centric Software, who is the proud owner of a souvenir jacket and a privileged witness to our relative elegance in the elements. Thank you to everyone who supported Albert Crew: thanks to you, this adventure has taken on a whole new dimension. See you next year, hopefully with a little more sunshine, a lot more sails... and as much energy as ever. See you at the next departure! — Simon and Prisca"),
    ],
    pullQuotes: [{ text: "Fun fact: Oscar is still alive and didn't fall overboard. We even have a mythical photo immortalising the moment!", attribution: "Albert Crew" }],
    media: [
      { file: "spi-dauphine-crew.jpg", caption: "The Albert Crew team", kind: "photo", rights: "GREEN", role: "hero" },
      { file: "spi-dauphine-oscar.jpg", caption: "Oscar falling into the water", credit: "© Flore Jaskulké", photographer: "Flore Jaskulké", kind: "photo", rights: "GREEN", role: "gallery" },
      { file: "spi-dauphine-boat.jpg", caption: "On board in the Bay of Saint-Tropez", kind: "photo", rights: "GREEN", role: "gallery" },
    ],
    facts: [
      { statement: "Albert School took part in the SPI Dauphine for the first time, with a team set up through the new Albert Crew association founded by Joseph Abdo, Flore Jaskulke and Victor de l'Epine.", category: "organisation", confidence: "VERIFIED_BY_SUBMISSION", sourceIndex: 0 },
      { statement: "Albert Crew finished 12th out of 45 teams and 3rd in the beer jug competition.", category: "result", confidence: "STATED_BY_CONTRIBUTOR", sourceIndex: 0 },
      { statement: "The SPI Dauphine brings together nearly 1,000 students and around fifty teams in the Bay of Saint-Tropez.", category: "metric", confidence: "STATED_BY_CONTRIBUTOR", sourceIndex: 0 },
      { statement: "Centric Software sponsored the crew; Bruce, EMEAR & LATAM Director of Partner Services, is thanked by name.", category: "organisation", confidence: "STATED_BY_CONTRIBUTOR", sourceIndex: 0 },
      { statement: "The founder's surname is spelled 'Jaskulke' in the text and 'Jaskulké' in the photo credit.", category: "person", confidence: "CONFLICTING", sourceIndex: 0, conflictGroup: "jaskulke-spelling" },
    ],
    people: [
      { name: "Joseph Abdo", role: "ORGANISER", campus: "paris" },
      { name: "Flore Jaskulke", role: "ORGANISER", campus: "paris" },
      { name: "Victor de l'Epine", role: "ORGANISER", campus: "paris" },
      { name: "Simon Flasaquier", role: "MENTIONED", campus: "paris" },
      { name: "Ines Hocine", role: "MENTIONED", campus: "paris" },
      { name: "Prisca Nobile", role: "MENTIONED", campus: "paris" },
      { name: "Oscar Mathey", role: "MENTIONED", campus: "paris" },
    ],
    organisations: [
      { name: "Albert Crew", type: "ASSOCIATION", role: "SUBJECT" },
      { name: "Centric Software", type: "COMPANY", role: "SPONSOR" },
    ],
    event: { title: "SPI Dauphine", dateText: "April 2025", location: "Bay of Saint-Tropez", campus: "paris", isUpcoming: false, organiser: "Albert Crew" },
    submissions: [
      {
        contributor: "joseph",
        storyType: "EVENT_RECAP",
        title: "Albert Crew at the SPI Dauphine — our first regatta",
        campuses: ["paris"],
        eventDateText: "April, five days",
        description:
          "Albert School took part in the SPI Dauphine for the very first time — one of the biggest student sports events in France, nearly 1,000 students and around fifty teams in the Bay of Saint-Tropez, five days. We (Joseph Abdo, Flore Jaskulke and Victor de l'Epine) set up the Albert Crew association and got a whole team on board. Wind, rain, uncertainty, and Yann, our skipper — a real captain in a storm, technical advice and good humour. Despite technical problems with the boat and wild weather we finished 12th out of 45 teams, with only five races, and 3rd in the beer jug competition. The weather in April: soaked socks, sweatshirts to wring out — next time, oilskins for everyone. Anecdote: on the first trip out in pouring rain, Oscar was half thrown out of the boat and saved by the small safety cable; our first instinct was to take a photo. Some jumped into the water for an icy swim. The team: Emilie Paulis, Prisca Nobile, Oscar Mathey, Simon Flasaquier, Ines Hocine, Léo Wang, Constantin Vuillier, Albert Curtil, Vadim Capton, Matheo Pradels, Sulian Brouard-Heulluy. Thanks to Centric Software for trusting us from our first steps on the water, and to Bruce, EMEAR & LATAM Director of Partner Services at Centric Software (proud owner of a souvenir jacket). See you next year with more sunshine. — Simon and Prisca wrote the acknowledgements.",
        peopleInvolved: "Joseph Abdo, Flore Jaskulke, Victor de l'Epine, Yann (skipper), Emilie Paulis, Prisca Nobile, Oscar Mathey, Simon Flasaquier, Ines Hocine, Léo Wang, Constantin Vuillier, Albert Curtil, Vadim Capton, Matheo Pradels, Sulian Brouard-Heulluy",
        organisationsInvolved: "Albert Crew, Centric Software, SPI Dauphine",
        media: ["spi-dauphine-crew.jpg", "spi-dauphine-boat.jpg"],
        status: "ACCEPTED",
        daysAfterOpen: 2,
      },
      {
        contributor: "simon",
        storyType: "PHOTO_STORY",
        title: "Photos from the SPI Dauphine (Albert Crew)",
        campuses: ["paris"],
        description: "Photos from the regatta: the crew, Oscar falling into the water (photo by Flore Jaskulké), the boat. Rights: all team members agree to be pictured.",
        peopleInvolved: "Albert Crew",
        media: ["spi-dauphine-oscar.jpg"],
        status: "ACCEPTED",
        daysAfterOpen: 3,
      },
    ],
    aiScores: { schoolRelevance: 74, studentRelevance: 90, uniqueness: 80, campusImportance: 76, timeliness: 74, editorialInterest: 92, visualRichness: 88, institutionalImportance: 48, businessDataRelevance: 10 },
  },
  {
    key: "campus-table-football",
    section: "campus-life",
    storyType: "ANECDOTE",
    title: "When Albert students compete with Mines engineers",
    campuses: ["paris"],
    status: "APPROVED",
    articleStatus: "APPROVED",
    priority: 44,
    kicker: "Anecdote — Paris",
    headline: "When Albert students compete with Mines engineers",
    standfirst: "A rescue mission for the Paris campus table football, peace be to its left hind leg.",
    byline: "Simon Flasaquier",
    targetLength: "SHORT",
    template: "NEWS_GRID",
    body: [
      p("What was supposed to be a relaxing break between lessons turned into a rescue mission worthy of the greatest engineers. With the table football on the Paris campus in danger of collapsing (peace be to its left hind leg), a team of students from Albert School x Mines de Paris joined forces to put it back together again."),
      p("Armed with technical know-how and a healthy dose of determination, they breathed new life into this icon of coffee breaks. Now rock-solid, the table football is ready for a new round of frenzied games... Some people see it as a simple DIY project. We see it as further proof that Albert School students are already on a par with Mines engineers."),
    ],
    media: [{ file: "table-football-1.jpg", caption: "The rescue of the Paris campus table football", credit: "© Simon Flasaquier", photographer: "Simon Flasaquier", kind: "photo", rights: "GREEN", role: "hero" }],
    facts: [{ statement: "Students from Albert School x Mines de Paris repaired the Paris campus table football.", category: "other", confidence: "VERIFIED_BY_SUBMISSION", sourceIndex: 0 }],
    submissions: [
      {
        contributor: "simon",
        storyType: "ANECDOTE",
        title: "Table football rescue on the Paris campus",
        campuses: ["paris"],
        description: "What was supposed to be a relaxing break between lessons turned into a rescue mission: with the Paris campus table football in danger of collapsing (peace be to its left hind leg), a team of students from Albert School x Mines de Paris put it back together. Rock-solid again. Some see a DIY project; we see proof that Albert students are on a par with Mines engineers. Photo by me.",
        media: ["table-football-1.jpg"],
        status: "ACCEPTED",
        daysAfterOpen: 4,
      },
    ],
    aiScores: { schoolRelevance: 50, studentRelevance: 70, uniqueness: 60, campusImportance: 60, timeliness: 50, editorialInterest: 66, visualRichness: 55, institutionalImportance: 20, businessDataRelevance: 5 },
  },
  {
    key: "campus-marseille-maths",
    section: "campus-life",
    storyType: "ACADEMIC_NEWS",
    title: "Marseille tops the maths assessments",
    campuses: ["marseille"],
    status: "APPROVED",
    articleStatus: "APPROVED",
    priority: 58,
    kicker: "Academic — Marseille",
    headline: "Forever first: Marseille tops the maths assessments!",
    standfirst: "Common maths assessments now run across all campuses. The Mediterranean campus leads the scores — and the Midterm data game on Pandas too.",
    byline: "Maelle Lalanne Carillon",
    targetLength: "SHORT",
    template: "NEWS_GRID",
    body: [
      p("For the past month, Albert School has been introducing maths assessments common to all campuses. The aim? To harmonise levels and validate skills in each maths chapter. The result? The Marseille campus has the highest scores!"),
      p("Is it the sunshine, the sea air of the Mediterranean, or simply the Nowacki effect? Because behind this performance is a man: David Nowacki, our maths teacher with a unique style, capable of transforming a probability table into a moment of pure joy (or almost)."),
      p("And that's not all: at the Midterm data game on Pandas, Marseille came out on top. A performance illustrated by the graphs... without any tricks, I promise! A thought for the other campuses: don't be discouraged, Marseille is happy to share its good vibes... but not its copies. :)"),
    ],
    media: [
      { file: "marseille-maths.jpg", caption: "Marseille students", credit: "© Simon Flasaquier", photographer: "Simon Flasaquier", kind: "photo", rights: "GREEN", role: "hero" },
      { file: "midterm-chart-marseille.png", caption: "Midterm Pandas chart — Marseille", kind: "chart", rights: "GREEN", role: "screenshot" },
      { file: "midterm-chart-lyon.png", caption: "Midterm Pandas chart — Lyon", kind: "chart", rights: "GREEN", role: "screenshot" },
    ],
    facts: [
      { statement: "Albert School introduced maths assessments common to all campuses; Marseille has the highest scores.", category: "result", confidence: "STATED_BY_CONTRIBUTOR", sourceIndex: 0 },
      { statement: "David Nowacki is the Marseille maths teacher.", category: "person", confidence: "VERIFIED_BY_SUBMISSION", sourceIndex: 0 },
      { statement: "Marseille also came out on top at the Midterm data game on Pandas.", category: "result", confidence: "STATED_BY_CONTRIBUTOR", sourceIndex: 0 },
    ],
    people: [{ name: "David Nowacki", role: "MENTIONED", campus: "marseille" }],
    submissions: [
      {
        contributor: "maelle",
        storyType: "ACADEMIC_NEWS",
        title: "Marseille tops the common maths assessments",
        campuses: ["marseille"],
        description: "For the past month, Albert School has been introducing maths assessments common to all campuses, to harmonise levels and validate skills in each chapter. Result: the Marseille campus has the highest scores! The sunshine, the sea air, or the Nowacki effect? David Nowacki, our maths teacher, transforms a probability table into a moment of pure joy (or almost). At the Midterm data game on Pandas, Marseille also came out on top — see the charts, no tricks. A thought for the other campuses: Marseille shares its good vibes but not its copies.",
        peopleInvolved: "David Nowacki",
        media: ["marseille-maths.jpg", "midterm-chart-marseille.png", "midterm-chart-lyon.png"],
        status: "ACCEPTED",
        daysAfterOpen: 5,
      },
    ],
    aiScores: { schoolRelevance: 70, studentRelevance: 80, uniqueness: 64, campusImportance: 92, timeliness: 70, editorialInterest: 74, visualRichness: 60, institutionalImportance: 55, businessDataRelevance: 40 },
  },
  {
    key: "event-admitted-party",
    section: "events",
    storyType: "UPCOMING_EVENT",
    title: "Admitted students party — Paris",
    campuses: ["paris"],
    eventDateText: "Wednesday 28 May 2025",
    status: "APPROVED",
    articleStatus: "APPROVED",
    priority: 60,
    kicker: "Save the date — Paris",
    headline: "Admitted to Albert School? Come and celebrate with us!",
    standfirst: "An Admitted Students Party on Wednesday 28 May at the Paris campus: meet your future classmates, current students and maybe your future godparent.",
    targetLength: "SHORT",
    template: "EVENT",
    body: [
      p("If you're here, it means you've made it — while hundreds of others didn't get selected! And we've got some exciting news for you: we're throwing an Admitted Students Party on Wednesday 28 May!"),
      h("WHY?"),
      p("To meet your fellow admitted students (and future friends!), and to visit the school."),
      h("WITH WHOM?"),
      p("You will chat with current students and ask all your questions about the school, Paris, events... You will have some snacks, listen to good music, and enjoy good vibes all around with everybody! During this special moment, you can enjoy time at the school, discover the culture and atmosphere of Albert, and maybe meet your future godfather or godmother!"),
      h("WHERE AND WHEN?"),
      p("See you at 18 Rue de Paradis, 75010 Paris, from 6:30 PM to 9:30 PM. Sign up here!"),
    ],
    media: [
      { file: "admitted-party-1.jpg", caption: "The Paris campus", kind: "photo", rights: "GREEN", role: "hero" },
      { file: "admitted-party-2.jpg", caption: "Students on the Paris campus", kind: "photo", rights: "GREEN", role: "gallery" },
    ],
    facts: [{ statement: "The Admitted Students Party takes place on Wednesday 28 May 2025, 6:30–9:30 PM, at 18 Rue de Paradis, 75010 Paris.", category: "date", confidence: "VERIFIED_BY_SUBMISSION", sourceIndex: 0 }],
    event: { title: "Admitted Students Party — Paris", dateText: "Wednesday 28 May 2025, 6:30–9:30 PM", location: "18 Rue de Paradis, 75010 Paris", campus: "paris", isUpcoming: true, organiser: "Albert School Paris" },
    submissions: [
      {
        contributor: "boris",
        storyType: "UPCOMING_EVENT",
        title: "Admitted Students Party — Wednesday 28 May, Paris",
        campuses: ["paris"],
        eventDateText: "Wednesday 28 May, 6:30–9:30 PM",
        description: "We're throwing an Admitted Students Party on Wednesday 28 May at 18 Rue de Paradis, 75010 Paris, from 6:30 PM to 9:30 PM. Why: to meet fellow admitted students and visit the school. With whom: current students to answer all questions about the school, Paris, events; snacks, good music, good vibes; discover the culture and atmosphere of Albert and maybe meet your future godfather or godmother. A sign-up link will be shared.",
        media: ["admitted-party-1.jpg", "admitted-party-2.jpg"],
        status: "ACCEPTED",
        daysAfterOpen: 6,
      },
    ],
    missingInformation: [{ key: "signup_url", label: "What is the sign-up link for the party?", severity: "high" }],
    aiScores: { schoolRelevance: 76, studentRelevance: 70, uniqueness: 40, campusImportance: 70, timeliness: 90, editorialInterest: 56, visualRichness: 50, institutionalImportance: 66, businessDataRelevance: 5 },
  },
  {
    key: "back-page-community",
    section: "back-page",
    storyType: "OTHER",
    title: "Back page: join Albert's Deep Dive, next events, true story",
    campuses: [],
    status: "APPROVED",
    articleStatus: "APPROVED",
    priority: 40,
    kicker: "Community",
    headline: "Join Albert's Deep Dive",
    standfirst: "Next year you'll have the chance to join the association. Think about it: you could become editor-in-chief like Barack Obama did at Harvard!",
    targetLength: "SHORT",
    template: "BACK_PAGE",
    body: [
      p("Next year you'll have the chance to join the association! It's so much fun to tell everyone about this wonderful school. Think about it, you'll be able to join from the very first days of the year! And if you put your mind to it, you could become editor-in-chief like Barack Obama did at Harvard!"),
      h("WE ARE LOOKING FOR OUR NEXT:"),
      box("Editorial pole", ["Journalist", "Prompt engineer", "Artistic director", "Director of corporate partnerships"]),
      box("Video pole", ["Video editor-in-chief", "Interview journalist", "Female voice-over"]),
      h("NEXT EVENTS"),
      l(["Saturday 24 May, Paris: JPO (open day).", "From Monday 2 to Wednesday 4 June, Paris: Office Pulse. Eugenia School launches a 72-hour hackathon to rethink office life. Objective: imagine the tool or the idea that will permanently transform the experience at work."]),
      h("SOLVE THE INTEGRAL IF YOU CAN"),
      p("This month's puzzle is on the printed page — bring your answer to the newsroom."),
      h("TRUE STORY"),
      p("\"If you come to Albert School, you'll have real-life case studies with companies. They will help you apply what you learn in class...\" — \"Hum... Sorry for interrupting you, you are very beautiful, are you married?\""),
    ],
    media: [
      { file: "true-story-comic.png", caption: "True story", credit: "© Simon Flasaquier", photographer: "Simon Flasaquier", kind: "photo", rights: "GREEN", role: "hero" },
      { file: "instagram.png", caption: "Follow us on Instagram", kind: "screenshot", rights: "GREEN", role: "gallery" },
    ],
    facts: [
      { statement: "The JPO (open day) in Paris is on Saturday 24 May 2025.", category: "date", confidence: "STATED_BY_CONTRIBUTOR", sourceIndex: 0 },
      { statement: "Eugenia School's Office Pulse hackathon runs from Monday 2 to Wednesday 4 June 2025 in Paris.", category: "date", confidence: "STATED_BY_CONTRIBUTOR", sourceIndex: 1 },
    ],
    organisations: [{ name: "Eugenia School", type: "SCHOOL", role: "MENTIONED" }],
    event: { title: "Office Pulse — 72-hour hackathon", dateText: "Monday 2 – Wednesday 4 June 2025", location: "Paris", campus: "paris", isUpcoming: true, organiser: "Eugenia School" },
    submissions: [
      {
        contributor: "milan",
        storyType: "OTHER",
        title: "Back page: recruitment for Albert's Deep Dive, JPO, puzzle, true story",
        campuses: [],
        description: "For the back page: Join Albert's Deep Dive next year — from the first days of the year; become editor-in-chief like Barack Obama at Harvard. We are looking for: Editorial pole — journalist, prompt engineer, artistic director, director of corporate partnerships; Video pole — video editor-in-chief, interview journalist, female voice-over. Next event: Saturday 24 May, Paris: JPO. Solve the integral if you can (puzzle image). True story comic strip by Simon. Follow us on Instagram.",
        media: ["true-story-comic.png", "instagram.png"],
        status: "ACCEPTED",
        daysAfterOpen: 7,
      },
      {
        contributor: "eugenia",
        storyType: "UPCOMING_EVENT",
        title: "Office Pulse — Eugenia School's 72-hour hackathon (2–4 June, Paris)",
        campuses: ["paris"],
        eventDateText: "Monday 2 – Wednesday 4 June",
        description: "Eugenia School launches Office Pulse, a 72-hour hackathon to rethink office life, from Monday 2 to Wednesday 4 June in Paris. Objective: imagine the tool or the idea that will permanently transform the experience at work.",
        organisationsInvolved: "Eugenia School",
        status: "ACCEPTED",
        daysAfterOpen: 7,
      },
    ],
    aiScores: { schoolRelevance: 60, studentRelevance: 72, uniqueness: 50, campusImportance: 40, timeliness: 80, editorialInterest: 60, visualRichness: 50, institutionalImportance: 40, businessDataRelevance: 10 },
  },
];
