import { type SeedStory, p, h, q, l } from "./types";

export const ACTUS_STORIES: SeedStory[] = [
  {
    key: "actus-executive-education",
    section: "actus",
    storyType: "SCHOOL_NEWS",
    title: "Training for professionals at Albert",
    campuses: [],
    status: "APPROVED",
    articleStatus: "APPROVED",
    priority: 72,
    kicker: "Albert Actus — interview with Lucie-Anna Oddon",
    headline: "Does the school train professionals? A seminar for 100 executives of a CAC 40 group",
    standfirst: "For a year and a half, Albert School has been training working professionals in data and AI. Lucie-Anna Oddon, in charge of executive education and corporate relations, explains why it matters for students too.",
    byline: "Ines Hocine",
    targetLength: "LONG",
    template: "ARTICLE_TWO_COLUMN",
    body: [
      p("This article is based on an interview with Lucie-Anna Oddon, who is in charge of both executive education and corporate relations at Albert School."),
      h("WHY IT'S GOOD NEWS FOR US TOO"),
      p("For the past year and a half, Albert School has been training more than just students. The school also offers training in data and artificial intelligence for working professionals. Yes, marketing, finance and HR directors come to us to brush up on subjects such as data analysis with Power BI or generative AI."),
      p("And no, it's not a separate course: the modules are taken from the same syllabus as our initial training. The aim is clear: to enable employees who are sometimes far removed from these subjects to understand what they can do with data... and how to do it. Some courses even take place directly on our campus."),
      p("The companies involved? The Ministry of Defence, Edmond de Rothschild, ODDO BHF (financial group), IQOO (Vivo subsidiary), KPMG (audit and consultancy firm), FDJ United (Française des Jeux group)..."),
      h("A VERY REAL IMPACT ON STUDENT LIFE"),
      p("Behind this range of courses is an important point: the same person is in charge of both executive education and Albert corporate relations. In other words, the logic is fluid. A company can come and train its teams, and then at the same time propose a Business Deep Dive case or look for a trainee."),
      p("These interactions strengthen the links between the school and companies, while raising the school's profile at a high level. Each new training session also becomes an opportunity to talk to decision-makers about Albert School. And we're not talking about a 'vague opportunity' here, but rather a strategic axis: in response to the shortage of data skills, a company can either recruit a student who has already been trained... or train its teams. And that's exactly what the school is offering, on both fronts."),
      h("ALBERT MIND, AI FOR STUDENTS... AND EXECUTIVES"),
      p("Albert Mind, our educational AI assistant, is also integrated into professional training courses. For example, in a two-day seminar for 100 executives from a major CAC 40 group, each participant was able to interact with the AI to assess their level of understanding, explore use cases adapted to their position, and better follow the content."),
      p("In a group of 100 people at very different levels, Albert Mind provides personalised support to complement traditional training. It also gives the company a more accurate picture of the skills of its teams. To put it plainly: it's not just a 'student' chatbot. It's a solid enough tool to support high-level profiles, and that makes our training all the more legitimate."),
    ],
    pullQuotes: [{ text: "A company can either recruit a student who has already been trained... or train its teams. The school offers both.", attribution: "Lucie-Anna Oddon, executive education & corporate relations" }],
    media: [
      { file: "lucie-anna-oddon.jpg", caption: "Lucie-Anna Oddon", kind: "photo", rights: "GREEN", role: "portrait" },
      { file: "training-hrds.jpg", caption: "Training for over 60 HR directors", kind: "photo", rights: "GREEN", role: "hero" },
    ],
    facts: [
      { statement: "Albert School has offered data and AI training to working professionals for a year and a half.", category: "other", confidence: "VERIFIED_BY_SUBMISSION", sourceIndex: 0 },
      { statement: "Client organisations include the Ministry of Defence, Edmond de Rothschild, ODDO BHF, IQOO, KPMG and FDJ United.", category: "organisation", confidence: "STATED_BY_CONTRIBUTOR", sourceIndex: 0 },
      { statement: "Albert Mind was used in a two-day seminar for 100 executives from a CAC 40 group.", category: "metric", confidence: "STATED_BY_CONTRIBUTOR", sourceIndex: 0 },
      { statement: "Lucie-Anna Oddon is in charge of both executive education and corporate relations.", category: "person", confidence: "VERIFIED_BY_SUBMISSION", sourceIndex: 0 },
    ],
    people: [{ name: "Lucie-Anna Oddon", role: "INTERVIEWEE" }],
    organisations: [
      { name: "KPMG", type: "COMPANY", role: "MENTIONED" },
      { name: "FDJ United", type: "COMPANY", role: "MENTIONED" },
      { name: "ODDO BHF", type: "COMPANY", role: "MENTIONED" },
      { name: "Edmond de Rothschild", type: "COMPANY", role: "MENTIONED" },
    ],
    submissions: [
      {
        contributor: "lucie-anna",
        storyType: "SCHOOL_NEWS",
        title: "Executive education at Albert School: what we do and why it matters for students",
        campuses: [],
        description:
          "For the past year and a half, Albert School has been training working professionals in data and AI, not only students: marketing, finance and HR directors come to brush up on data analysis with Power BI or generative AI. It's not a separate course — the modules come from the same syllabus as the initial training, so employees far from these subjects understand what they can do with data and how. Some courses take place on campus. Companies: the Ministry of Defence, Edmond de Rothschild, ODDO BHF (financial group), IQOO (Vivo subsidiary), KPMG (audit and consultancy), FDJ United (Française des Jeux group)... The same person is in charge of executive education and corporate relations, so the logic is fluid: a company can train its teams and, at the same time, propose a Business Deep Dive case or look for a trainee. It strengthens links with companies and raises the school's profile: in response to the shortage of data skills, a company can recruit a trained student or train its teams — we offer both. Albert Mind is also integrated into professional training: in a two-day seminar for 100 executives from a major CAC 40 group, each participant interacted with the AI to assess their understanding, explore use cases for their position and follow the content. It gives the company an accurate picture of its teams' skills; it's not just a 'student' chatbot. Photo: training for over 60 HRDs.",
        peopleInvolved: "Lucie-Anna Oddon",
        organisationsInvolved: "Ministry of Defence, Edmond de Rothschild, ODDO BHF, IQOO, KPMG, FDJ United",
        whyItMatters: "Explains a strategic axis of the school and its direct link with BDDs and internships.",
        media: ["lucie-anna-oddon.jpg", "training-hrds.jpg"],
        status: "ACCEPTED",
        daysAfterOpen: 5,
      },
    ],
    aiScores: { schoolRelevance: 90, studentRelevance: 74, uniqueness: 70, campusImportance: 60, timeliness: 66, editorialInterest: 72, visualRichness: 58, institutionalImportance: 94, businessDataRelevance: 80 },
  },
  {
    key: "actus-cis",
    section: "actus",
    storyType: "SCHOOL_NEWS",
    title: "Mines Paris PSL and Albert School join the Council of International Schools",
    campuses: [],
    status: "APPROVED",
    articleStatus: "APPROVED",
    priority: 60,
    kicker: "Albert Actus",
    headline: "Mines Paris PSL — and Albert School by extension — join the Council of International Schools",
    standfirst: "The CIS brings together 1,530 schools and universities in 122 countries. Membership is a guarantee of international quality, and it has to be earned again every two or three years.",
    byline: "Milan Viallet",
    targetLength: "SHORT",
    template: "NEWS_GRID",
    body: [
      h("HAVE YOU HEARD OF THE CIS?"),
      p("You may not be familiar with the Council of International Schools, but it is an internationally recognised network that attests to the quality and international outlook of the courses it offers. It brings together 1,530 schools and universities in 122 countries, including around twenty in France, including Polytechnique, Centrale, EDHEC, ESCP, emlyon, Sciences Po and INSA Lyon. And recently, Mines de Paris joined the organisation, and therefore Albert School x Mines de Paris by extension."),
      p("These universities can only be grouped together because they teach in English and have links with American universities in particular. The mission of the CIS is to promote effective educational practices to produce healthy, interculturally competent and socially responsible citizens of the world. The CIS offers an international accreditation recognised as a guarantee of quality. Universities around the world value students from CIS-accredited schools for the rigour of their training, their intercultural awareness and their preparation for life in a globalised world."),
      h("UNFORTUNATELY, IT WON'T LAST FOREVER"),
      p("Every two or three years, according to the latest CIS protocol, a re-evaluation is required for schools. This involves a 12–18 month self-evaluation involving the whole educational community, followed by a week-long visit by colleagues from other CIS member schools, who impartially verify the data provided in the detailed report and in turn offer praise for successes achieved as well as suggestions for future progress. If all goes according to plan, the school will be re-accredited."),
    ],
    media: [{ file: "cis-logo.jpg", caption: "Council of International Schools", kind: "logo", rights: "GREEN", role: "logo" }],
    facts: [
      { statement: "The Council of International Schools brings together 1,530 schools and universities in 122 countries.", category: "metric", confidence: "STATED_BY_CONTRIBUTOR", sourceIndex: 0 },
      { statement: "Mines de Paris recently joined the CIS, and therefore Albert School x Mines de Paris by extension.", category: "organisation", confidence: "STATED_BY_CONTRIBUTOR", sourceIndex: 0, notes: "Single source; consider confirming with the administration." },
      { statement: "CIS re-evaluation is required every two or three years (12–18 month self-evaluation plus a week-long peer visit).", category: "other", confidence: "STATED_BY_CONTRIBUTOR", sourceIndex: 0 },
    ],
    organisations: [
      { name: "Council of International Schools", type: "INSTITUTION", role: "SUBJECT" },
      { name: "Mines Paris PSL", type: "SCHOOL", role: "PARTNER" },
    ],
    submissions: [
      {
        contributor: "milan",
        storyType: "SCHOOL_NEWS",
        title: "Mines Paris PSL and Albert School joining the Council of International Schools",
        campuses: [],
        description:
          "The Council of International Schools (CIS) is an internationally recognised network attesting to the quality and international outlook of the courses it offers: 1,530 schools and universities in 122 countries, around twenty in France (Polytechnique, Centrale, EDHEC, ESCP, emlyon, Sciences Po, INSA Lyon). Recently Mines de Paris joined, and therefore Albert School x Mines de Paris by extension. Members teach in English and have links with American universities. Mission: promote effective educational practices to produce healthy, interculturally competent and socially responsible citizens of the world. The accreditation is recognised as a guarantee of quality; universities value CIS-accredited students for the rigour of their training and intercultural awareness. Every two or three years a re-evaluation is required: 12–18 month self-evaluation involving the whole educational community, then a week-long visit by colleagues from other CIS member schools who verify the data and offer praise and suggestions.",
        organisationsInvolved: "Council of International Schools, Mines Paris PSL",
        media: ["cis-logo.jpg"],
        status: "ACCEPTED",
        daysAfterOpen: 3,
      },
    ],
    missingInformation: [{ key: "official_source", label: "Is there an official announcement (link) from Mines Paris PSL or the CIS we can reference?", severity: "medium" }],
    aiScores: { schoolRelevance: 78, studentRelevance: 60, uniqueness: 55, campusImportance: 40, timeliness: 64, editorialInterest: 52, visualRichness: 20, institutionalImportance: 90, businessDataRelevance: 30 },
  },
  {
    key: "actus-tribune-geneve",
    section: "actus",
    storyType: "SCHOOL_NEWS",
    title: "Albert School in La Tribune de Genève",
    campuses: ["geneva"],
    status: "APPROVED",
    articleStatus: "APPROVED",
    priority: 66,
    kicker: "Albert Actus — press",
    headline: "\"A European Stanford\": Albert School in La Tribune de Genève",
    standfirst: "The Geneva daily devoted an article to the opening of the Geneva campus, the school's partners and investors, and what makes the training unique.",
    byline: "Milan Viallet",
    targetLength: "SHORT",
    template: "NEWS_GRID",
    body: [
      p("We've been treated to an article in La Tribune de Genève! The article appeared last Friday."),
      h("HERE'S WHAT THE ARTICLE IS ABOUT"),
      p("It opens with a quote from Grégoire: \"Our aim is to become a benchmark for innovation and quality, a European Stanford\". That sets the tone! The article goes on to talk about the opening of the Geneva campus, its partners, and then explains the uniqueness of our training and what it consists of — and according to them, we do engineering!"),
      p("Apart from that, the article is coherent, but note that they compare the prices of HEC Paris to those of Albert School Geneva (tuition fees are necessarily much higher in Switzerland). Then there's a focus on what Albert Mind is going to be: trainees, get ready for some feedback! The article also looks at the prestigious investors who helped create the school. You can read it on the school's website, in Media then Press."),
    ],
    pullQuotes: [{ text: "Our aim is to become a benchmark for innovation and quality, a European Stanford.", attribution: "Grégoire, quoted in La Tribune de Genève" }],
    media: [
      { file: "tribune-de-geneve-reading.jpg", caption: "Matteo Bianchi, reading La Tribune de Genève", credit: "© Grégoire Genest", photographer: "Grégoire Genest", kind: "photo", rights: "GREEN", role: "hero" },
      { file: "tribune-de-geneve-article.jpg", caption: "The article", kind: "photo", rights: "YELLOW", role: "gallery" },
    ],
    facts: [
      { statement: "La Tribune de Genève published an article about Albert School and the opening of its Geneva campus.", category: "other", confidence: "VERIFIED_BY_SUBMISSION", sourceIndex: 0 },
      { statement: "The article opens with a quote from Grégoire: 'Our aim is to become a benchmark for innovation and quality, a European Stanford'.", category: "other", confidence: "STATED_BY_CONTRIBUTOR", sourceIndex: 0 },
      { statement: "The exact publication date is not stated ('last Friday').", category: "date", confidence: "INFERRED", sourceIndex: 0 },
    ],
    quotes: [{ text: "Our aim is to become a benchmark for innovation and quality, a European Stanford.", speaker: "Grégoire", role: "quoted in La Tribune de Genève", sourceIndex: 0, pullQuote: true }],
    people: [{ name: "Matteo Bianchi", role: "MENTIONED", campus: "geneva" }],
    organisations: [{ name: "La Tribune de Genève", type: "MEDIA", role: "SUBJECT" }],
    submissions: [
      {
        contributor: "milan",
        storyType: "SCHOOL_NEWS",
        title: "Albert School in La Tribune de Genève",
        campuses: ["geneva"],
        eventDateText: "last Friday",
        description:
          "We've been treated to an article in La Tribune de Genève, published last Friday. It opens with a quote from Grégoire: 'Our aim is to become a benchmark for innovation and quality, a European Stanford'. It talks about the opening of the Geneva campus, its partners, then explains the uniqueness of our training (according to them, we do engineering!). They compare the prices of HEC Paris with Albert School Geneva (tuition fees are necessarily much higher in Switzerland). Then a focus on what Albert Mind is going to be, and the prestigious investors who helped create the school. It can be read on the school's website in Media > Press. Photo: Matteo Bianchi reading La Tribune de Genève (© Grégoire Genest), and a photo of the article.",
        peopleInvolved: "Grégoire, Matteo Bianchi",
        organisationsInvolved: "La Tribune de Genève",
        media: ["tribune-de-geneve-reading.jpg", "tribune-de-geneve-article.jpg"],
        status: "ACCEPTED",
        daysAfterOpen: 4,
      },
    ],
    missingInformation: [
      { key: "article_url", label: "Please share the link to the Tribune de Genève article (or the press page on the school website).", severity: "medium" },
      { key: "publication_date", label: "On which date was the article published?", severity: "medium" },
      { key: "article_photo_rights", label: "Can we reproduce the photo of the printed article (newspaper copyright)?", severity: "high" },
    ],
    aiScores: { schoolRelevance: 84, studentRelevance: 62, uniqueness: 66, campusImportance: 90, timeliness: 70, editorialInterest: 68, visualRichness: 60, institutionalImportance: 88, businessDataRelevance: 30 },
  },
  {
    key: "actus-albert-mind",
    section: "actus",
    storyType: "SCHOOL_NEWS",
    title: "Albert Mind: your new ally for success",
    campuses: [],
    status: "APPROVED",
    articleStatus: "APPROVED",
    priority: 74,
    kicker: "Albert Actus — product",
    headline: "Albert Mind: your new ally for success",
    standfirst: "Save time, understand your lessons better and pass your exams: the intelligent assistant designed for Albert and Eugenia students draws on the school's own courses. Pilot classes are testing it now.",
    targetLength: "MEDIUM",
    template: "ARTICLE_TWO_COLUMN",
    body: [
      p("Save time, understand your lessons better and pass your exams: that's what Albert Mind, the new intelligent assistant designed for Albert and Eugenia students, offers. Unlike traditional AIs, Albert Mind doesn't just give general answers: it draws on the courses, teaching materials and the school's internal resources to provide precise explanations tailored to the programme and learning pace of each student."),
      h("IN PRACTICAL TERMS, HOW DOES ALBERT MIND HELP YOU?"),
      l(["Before the course: get a head start with a structured overview of key concepts so that you arrive at class ready to understand and participate.", "During revision: review the essential points in question-and-answer mode, test your understanding and move forward in a targeted and effective way."]),
      h("NEXT STEPS"),
      p("A new version of Albert Mind is already under development. It will provide support throughout the academic career, including the generation of personalised plans to prepare for interviews, professional projects or exams. But at the end of the day, we're all wondering what makes Albert Mind different from a classic ChatGPT?"),
      q("Albert Mind evolves with the student, learning from their habits, strengths and difficulties, to offer a truly tailor-made experience.", "Othmane AitBoumlik, developer of Albert Mind"),
      h("HOW FAR HAS THE PROJECT GOT?"),
      p("Albert Mind is currently being tested with several pilot classes. The feedback is being used to refine the tool and enhance its features, with a view to wider deployment at the start of the new school year. A huge thank you to Othmane and the whole team for their passionate work in making this adventure possible!"),
    ],
    pullQuotes: [{ text: "Albert Mind evolves with the student, learning from their habits, strengths and difficulties.", attribution: "Othmane AitBoumlik, developer" }],
    media: [
      { file: "albert-mind-othmane.jpg", caption: "Othmane AitBoumlik, developer of Albert Mind", kind: "photo", rights: "GREEN", role: "portrait" },
      { file: "albert-mind-banner.png", caption: "Albert Mind", kind: "logo", rights: "GREEN", role: "hero" },
    ],
    facts: [
      { statement: "Albert Mind is an intelligent assistant for Albert and Eugenia students that draws on the school's courses and internal resources.", category: "other", confidence: "VERIFIED_BY_SUBMISSION", sourceIndex: 0 },
      { statement: "Albert Mind is being tested with several pilot classes, with wider deployment planned for the start of the new school year.", category: "date", confidence: "STATED_BY_CONTRIBUTOR", sourceIndex: 0 },
      { statement: "Othmane AitBoumlik is the developer of Albert Mind.", category: "person", confidence: "VERIFIED_BY_SUBMISSION", sourceIndex: 0 },
    ],
    quotes: [{ text: "Albert Mind evolves with the student, learning from their habits, strengths and difficulties, to offer a truly tailor-made experience.", speaker: "Othmane AitBoumlik", role: "developer of Albert Mind", sourceIndex: 0, pullQuote: true }],
    people: [{ name: "Othmane AitBoumlik", role: "INTERVIEWEE" }],
    organisations: [{ name: "Eugenia School", type: "SCHOOL", role: "MENTIONED" }],
    submissions: [
      {
        contributor: "othmane",
        storyType: "SCHOOL_NEWS",
        title: "Albert Mind — where the project stands",
        campuses: [],
        description:
          "Albert Mind is the new intelligent assistant designed for Albert and Eugenia students: save time, understand your lessons better and pass your exams. Unlike traditional AIs it doesn't just give general answers: it draws on the courses, teaching materials and internal resources of the school to provide precise explanations tailored to each student's programme and pace. Before the course: a structured overview of key concepts. During revision: question-and-answer mode to test understanding. A new version is under development: support throughout the academic career, with personalised plans to prepare for interviews, professional projects or exams. What makes it different from a classic ChatGPT? Albert Mind evolves with the student, learning from their habits, strengths and difficulties, to offer a truly tailor-made experience. Albert Mind is currently being tested with several pilot classes; feedback is refining the tool with a view to wider deployment at the start of the new school year.",
        peopleInvolved: "Othmane AitBoumlik and the Albert Mind team",
        quotes: "\"Albert Mind evolves with the student, learning from their habits, strengths and difficulties, to offer a truly tailor-made experience.\" — Othmane, developer",
        media: ["albert-mind-othmane.jpg", "albert-mind-banner.png"],
        status: "ACCEPTED",
        daysAfterOpen: 6,
      },
    ],
    aiScores: { schoolRelevance: 90, studentRelevance: 92, uniqueness: 72, campusImportance: 60, timeliness: 78, editorialInterest: 76, visualRichness: 50, institutionalImportance: 86, businessDataRelevance: 82 },
  },
  {
    key: "actus-office-hours",
    section: "actus",
    storyType: "SCHOOL_NEWS",
    title: "Administrative office hours",
    campuses: ["paris", "lyon", "marseille"],
    status: "APPROVED",
    articleStatus: "APPROVED",
    priority: 50,
    kicker: "Albert Actus — campus",
    headline: "Office hours: the administration opens its doors at lunchtime",
    standfirst: "Courses, internships, associations, exams — or just a chat. New lunch-break office hours on all three French campuses.",
    byline: "Khadidja Addi",
    targetLength: "SHORT",
    template: "NEWS_GRID",
    body: [
      p("For the past week, a new event has been spicing up our lunch breaks: administrative office hours! In Paris, it's from 1pm to 2pm, Tuesday to Friday, with Marie, Grégoire, Mathieu and Édouard. In Lyon, it's every lunchtime, from 1.30pm to 2pm, with Kevin. And in Marseille, it's on Mondays and Thursdays from 1pm to 2pm."),
      p("They offer you the chance to discuss all aspects of your life at school: courses, work placements, associations, exams... or why not just have a chat. Some people even say that Marie already knows the subjects for the next mid-term. But she remains unperturbed by attempts at bribery..."),
      p("So don't wait any longer, make the most of your lunch break and go over and say hello. And if it's really urgent, don't panic, the admin is available outside these times."),
    ],
    media: [{ file: "office-hours-admin.jpg", caption: "The administration team during office hours", kind: "photo", rights: "YELLOW", role: "hero" }],
    facts: [
      { statement: "Office hours: Paris 1–2pm Tuesday to Friday (Marie, Grégoire, Mathieu, Édouard); Lyon 1.30–2pm every lunchtime (Kevin); Marseille Mondays and Thursdays 1–2pm.", category: "other", confidence: "VERIFIED_BY_SUBMISSION", sourceIndex: 0 },
    ],
    submissions: [
      {
        contributor: "khadidja",
        storyType: "SCHOOL_NEWS",
        title: "New: administrative office hours at lunchtime",
        campuses: ["paris", "lyon", "marseille"],
        description:
          "For the past week, a new event has been spicing up our lunch breaks: administrative office hours! Paris: 1pm to 2pm, Tuesday to Friday, with Marie, Grégoire, Mathieu and Édouard. Lyon: every lunchtime from 1.30pm to 2pm with Kevin. Marseille: Mondays and Thursdays from 1pm to 2pm. You can discuss everything: courses, work placements, associations, exams... or just have a chat. Some say Marie already knows the subjects for the next mid-term, but she remains unperturbed by attempts at bribery. If it's really urgent, the admin is available outside these times.",
        peopleInvolved: "Marie, Grégoire, Mathieu, Édouard, Kevin",
        media: ["office-hours-admin.jpg"],
        status: "ACCEPTED",
        daysAfterOpen: 1,
      },
      {
        contributor: "kevin",
        storyType: "SCHOOL_NEWS",
        title: "Permanences administratives à Lyon",
        campuses: ["lyon"],
        description: "À Lyon, permanence administrative tous les midis de 13h30 à 14h avec Kevin : cours, stages, associations, examens, ou simplement pour discuter.",
        peopleInvolved: "Kevin",
        status: "DUPLICATE",
        daysAfterOpen: 2,
      },
    ],
    missingInformation: [{ key: "photo_people", label: "Who is on the office-hours photo, and do they agree to appear?", severity: "medium" }],
    aiScores: { schoolRelevance: 70, studentRelevance: 80, uniqueness: 40, campusImportance: 75, timeliness: 80, editorialInterest: 58, visualRichness: 40, institutionalImportance: 60, businessDataRelevance: 10 },
  },
  {
    key: "data-under-pressure",
    section: "data-business",
    storyType: "DATA_AI_BUSINESS_INSIGHT",
    title: "Business & Data under pressure",
    campuses: [],
    status: "SELECTED",
    articleStatus: "IN_EDITING",
    priority: 62,
    kicker: "Business & Data under pressure",
    headline: "AI in the classroom, the regulation wave and the antitrust push: five movements to watch",
    standfirst: "As 2025 progresses, political and social developments are rapidly reshaping the landscape for businesses and data. A snapshot of what students and professionals in business and data must keep an eye on.",
    byline: "Cynda Ben Abdessalem",
    targetLength: "LONG",
    template: "NEWS_GRID",
    body: [
      p("As we progress through 2025, several major political and social developments are rapidly reshaping the landscape for businesses and the world of data. Here's a snapshot of a few important movements that students and professionals in business and data must keep an eye on."),
      h("INTEGRATING AI INTO EDUCATION IN THE US"),
      p("A presidential executive order sets out a national policy to promote AI literacy and prepare a workforce ready for future technological challenges. Key measures include the integration of AI into educational programmes from kindergarten to high school; comprehensive AI training for educators; early exposure of students to AI concepts to develop a future generation of American AI innovators; and the creation of a White House AI Education Task Force to oversee the implementation of these initiatives."),
      p("This initiative comes amid calls from the private sector, including more than 200 CEOs of major companies such as Microsoft, Uber and LinkedIn, to make AI and computer science education mandatory for high school graduation. In short, although the decree does not make AI education compulsory at federal level, it does establish a clear national strategy for integrating AI into education and training teachers."),
      h("THE GLOBAL AI REGULATION WAVE"),
      p("Following the EU's landmark AI Act, many countries — including the United States, Canada and Japan — are rushing to establish their own regulatory frameworks. Businesses handling data-driven AI models must now comply with transparency, fairness and risk management obligations. Companies using AI in sectors like finance, healthcare and recruitment face especially strict new rules. Data governance is no longer optional; it's becoming a legal necessity across industries."),
      h("CHINA'S NEW DATA EXPORT CONTROLS"),
      p("China recently tightened its data export laws, making it harder for companies to transfer sensitive information out of the country. Multinational corporations operating in China must now undergo complex security assessments before moving customer or operational data abroad. This move forces businesses to rethink their cloud strategies and supply chains, emphasising data localisation and local partnerships to stay compliant."),
      h("THE ANTITRUST PUSH AGAINST BIG TECH"),
      p("In the US, antitrust scrutiny against giants like Amazon, Apple and Google has intensified. Several lawsuits argue these companies abuse their market dominance through data-driven advantages. If successful, these cases could radically change how tech platforms collect and monetise user data. For startups and smaller players, this could open new competitive spaces — provided they handle data ethically and securely."),
      h("THE AI ACT AND THE EUROPEAN UNION"),
      p("The European Union's AI Act is the first comprehensive regulatory framework for artificial intelligence in the world. This landmark legislation classifies AI systems based on risk levels — from minimal to high — and imposes strict rules on how high-risk systems can be developed, deployed and monitored. For students and professionals, this is a pivotal moment: the Act requires companies to ensure transparency, explainability and data traceability in AI systems, which reshapes the way organisations think about model development, data governance and customer trust. Ultimately, the AI Act doesn't just set new rules — it sets a new global standard. And for Europe, it may become a competitive advantage, positioning the continent as a leader in trustworthy and sustainable AI."),
    ],
    media: [
      { file: "business-data-banner.jpg", caption: "Business & Data under pressure", credit: "© Simon Flasaquier", photographer: "Simon Flasaquier", kind: "photo", rights: "GREEN", role: "hero" },
      { file: "ai-education-us.jpg", caption: "AI literacy from kindergarten to high school", kind: "photo", rights: "YELLOW", role: "gallery" },
      { file: "ai-regulation.png", caption: "The global AI regulation wave", kind: "chart", rights: "YELLOW", role: "gallery" },
    ],
    facts: [
      { statement: "A US executive order promotes AI literacy, teacher training and a White House AI Education Task Force.", category: "other", confidence: "STATED_BY_CONTRIBUTOR", sourceIndex: 0, notes: "External claim: source URL required before publication." },
      { statement: "More than 200 CEOs (including Microsoft, Uber and LinkedIn) called for mandatory AI and computer science education for high school graduation.", category: "metric", confidence: "STATED_BY_CONTRIBUTOR", sourceIndex: 0, notes: "External claim: source URL required." },
      { statement: "The submission states that the EU formally approved the AI Act in April 2025; the AI Act was adopted in 2024, so this date must be checked against a primary source.", category: "date", confidence: "CONFLICTING", sourceIndex: 0, conflictGroup: "ai-act-date" },
    ],
    organisations: [{ name: "European Union", type: "INSTITUTION", role: "MENTIONED" }],
    submissions: [
      {
        contributor: "cynda",
        storyType: "DATA_AI_BUSINESS_INSIGHT",
        title: "Business & Data under pressure — five movements to watch",
        campuses: [],
        description:
          "As we progress through 2025, several major political and social developments are reshaping the landscape for businesses and data. 1) Integrating AI into education in the US: an executive order sets a national policy to promote AI literacy — integration of AI from kindergarten to high school, teacher training, early exposure, a White House AI Education Task Force; more than 200 CEOs (Microsoft, Uber, LinkedIn) call for AI and computer science education to be mandatory for high school graduation; the decree does not make AI education compulsory at federal level but establishes a national strategy. 2) The global AI regulation wave: after the EU AI Act, the US, Canada and Japan are establishing their own frameworks; transparency, fairness and risk-management obligations; strict rules in finance, healthcare and recruitment. 3) China's new data export controls: complex security assessments before moving customer or operational data abroad; data localisation and local partnerships. 4) The antitrust push against Big Tech: lawsuits against Amazon, Apple and Google over data-driven dominance; opportunities for startups that handle data ethically. 5) The AI Act: in April 2025 the EU formally approved the AI Act, the first comprehensive AI regulatory framework; risk-based classification; transparency, explainability and data traceability; a new global standard and a possible competitive advantage for Europe.",
        whyItMatters: "Context for every Albert student who will work with data: regulation and geopolitics are becoming part of the job.",
        media: ["business-data-banner.jpg", "ai-education-us.jpg", "ai-regulation.png"],
        status: "NEEDS_REVIEW",
        daysAfterOpen: 6,
      },
    ],
    missingInformation: [
      { key: "source_urls", label: "Please add the source links for each of the five items (official texts or press articles).", severity: "high" },
      { key: "image_rights", label: "Where do the two illustration images come from, and are they licensed for print?", severity: "high" },
    ],
    warnings: [{ code: "EXTERNAL_UNSOURCED", message: "External news items have no source URLs. The Business & Data module requires editor-approved sources before publication.", severity: "error" }],
    aiScores: { schoolRelevance: 50, studentRelevance: 78, uniqueness: 45, campusImportance: 30, timeliness: 85, editorialInterest: 66, visualRichness: 55, institutionalImportance: 40, businessDataRelevance: 92 },
  },
];
